# Generated by Django 4.2.7 on 2026-03-29 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workoutlog',
            options={'ordering': ['-completed_at']},
        ),
    ]
