--
-- PostgreSQL database dump
--

-- Dumped from database version 16.6
-- Dumped by pg_dump version 17.2

-- Started on 2026-04-13 17:09:34

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 5 (class 2615 OID 112029)
-- Name: public; Type: SCHEMA; Schema: -; Owner: -
--

-- *not* creating schema, since initdb creates it


--
-- TOC entry 5141 (class 0 OID 0)
-- Dependencies: 5
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON SCHEMA public IS '';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 222 (class 1259 OID 112054)
-- Name: auth_group; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


--
-- TOC entry 221 (class 1259 OID 112053)
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 224 (class 1259 OID 112062)
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


--
-- TOC entry 223 (class 1259 OID 112061)
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 220 (class 1259 OID 112048)
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


--
-- TOC entry 219 (class 1259 OID 112047)
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 234 (class 1259 OID 112155)
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id bigint NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


--
-- TOC entry 233 (class 1259 OID 112154)
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 218 (class 1259 OID 112040)
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


--
-- TOC entry 217 (class 1259 OID 112039)
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 216 (class 1259 OID 112032)
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


--
-- TOC entry 215 (class 1259 OID 112031)
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 247 (class 1259 OID 112279)
-- Name: django_session; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


--
-- TOC entry 236 (class 1259 OID 112176)
-- Name: exercises_equipment; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.exercises_equipment (
    id bigint NOT NULL,
    name character varying(100) NOT NULL,
    slug character varying(100) NOT NULL
);


--
-- TOC entry 235 (class 1259 OID 112175)
-- Name: exercises_equipment_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.exercises_equipment ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.exercises_equipment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 240 (class 1259 OID 112198)
-- Name: exercises_exercise; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.exercises_exercise (
    id bigint NOT NULL,
    name character varying(200) NOT NULL,
    slug character varying(200) NOT NULL,
    description text NOT NULL,
    instructions text NOT NULL,
    benefits text NOT NULL,
    precautions text NOT NULL,
    exercise_type character varying(20) NOT NULL,
    difficulty character varying(20) NOT NULL,
    video_url character varying(200) NOT NULL,
    video_file character varying(100),
    image character varying(100),
    calories_per_hour integer NOT NULL,
    is_active boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    image_url character varying(500),
    CONSTRAINT exercises_exercise_calories_per_hour_check CHECK ((calories_per_hour >= 0))
);


--
-- TOC entry 242 (class 1259 OID 112211)
-- Name: exercises_exercise_equipment; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.exercises_exercise_equipment (
    id bigint NOT NULL,
    exercise_id bigint NOT NULL,
    equipment_id bigint NOT NULL
);


--
-- TOC entry 241 (class 1259 OID 112210)
-- Name: exercises_exercise_equipment_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.exercises_exercise_equipment ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.exercises_exercise_equipment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 239 (class 1259 OID 112197)
-- Name: exercises_exercise_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.exercises_exercise ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.exercises_exercise_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 259 (class 1259 OID 112382)
-- Name: exercises_exercise_muscle_groups; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.exercises_exercise_muscle_groups (
    id bigint NOT NULL,
    exercise_id bigint NOT NULL,
    musclegroup_id bigint NOT NULL
);


--
-- TOC entry 258 (class 1259 OID 112381)
-- Name: exercises_exercise_muscle_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.exercises_exercise_muscle_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.exercises_exercise_muscle_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 244 (class 1259 OID 112217)
-- Name: exercises_exercise_primary_muscles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.exercises_exercise_primary_muscles (
    id bigint NOT NULL,
    exercise_id bigint NOT NULL,
    musclegroup_id bigint NOT NULL
);


--
-- TOC entry 243 (class 1259 OID 112216)
-- Name: exercises_exercise_primary_muscles_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.exercises_exercise_primary_muscles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.exercises_exercise_primary_muscles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 246 (class 1259 OID 112223)
-- Name: exercises_exercise_secondary_muscles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.exercises_exercise_secondary_muscles (
    id bigint NOT NULL,
    exercise_id bigint NOT NULL,
    musclegroup_id bigint NOT NULL
);


--
-- TOC entry 245 (class 1259 OID 112222)
-- Name: exercises_exercise_secondary_muscles_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.exercises_exercise_secondary_muscles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.exercises_exercise_secondary_muscles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 238 (class 1259 OID 112186)
-- Name: exercises_musclegroup; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.exercises_musclegroup (
    id bigint NOT NULL,
    name character varying(100) NOT NULL,
    slug character varying(100) NOT NULL,
    description text NOT NULL,
    icon character varying(50),
    is_group boolean NOT NULL
);


--
-- TOC entry 237 (class 1259 OID 112185)
-- Name: exercises_musclegroup_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.exercises_musclegroup ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.exercises_musclegroup_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 257 (class 1259 OID 112356)
-- Name: progress_progressentry; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.progress_progressentry (
    id bigint NOT NULL,
    image character varying(100),
    weight numeric(5,2),
    comment text,
    created_at date NOT NULL,
    user_id bigint NOT NULL
);


--
-- TOC entry 256 (class 1259 OID 112355)
-- Name: progress_progressentry_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.progress_progressentry ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.progress_progressentry_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 255 (class 1259 OID 112350)
-- Name: progress_workoutlog; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.progress_workoutlog (
    id bigint NOT NULL,
    completed_at timestamp with time zone NOT NULL,
    user_id bigint NOT NULL,
    workout_day_id bigint NOT NULL
);


--
-- TOC entry 254 (class 1259 OID 112349)
-- Name: progress_workoutlog_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.progress_workoutlog ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.progress_workoutlog_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 249 (class 1259 OID 112289)
-- Name: training_dayexercise; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.training_dayexercise (
    id bigint NOT NULL,
    exercise_id bigint NOT NULL,
    workout_day_id bigint NOT NULL,
    "order" integer NOT NULL,
    reps integer NOT NULL,
    sets integer NOT NULL,
    CONSTRAINT training_dayexercise_order_check CHECK (("order" >= 0)),
    CONSTRAINT training_dayexercise_reps_20dc60f0_check CHECK ((reps >= 0)),
    CONSTRAINT training_dayexercise_sets_check CHECK ((sets >= 0))
);


--
-- TOC entry 248 (class 1259 OID 112288)
-- Name: training_dayexercise_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.training_dayexercise ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.training_dayexercise_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 251 (class 1259 OID 112295)
-- Name: training_workoutday; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.training_workoutday (
    id bigint NOT NULL,
    day_number integer NOT NULL,
    plan_id bigint NOT NULL,
    CONSTRAINT training_workoutday_day_number_check CHECK ((day_number >= 0))
);


--
-- TOC entry 250 (class 1259 OID 112294)
-- Name: training_workoutday_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.training_workoutday ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.training_workoutday_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 253 (class 1259 OID 112302)
-- Name: training_workoutplan; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.training_workoutplan (
    id bigint NOT NULL,
    title character varying(255) NOT NULL,
    start_date date NOT NULL,
    end_date date NOT NULL,
    created_at timestamp with time zone NOT NULL,
    user_id bigint NOT NULL,
    is_active boolean NOT NULL
);


--
-- TOC entry 252 (class 1259 OID 112301)
-- Name: training_workoutplan_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.training_workoutplan ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.training_workoutplan_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 226 (class 1259 OID 112094)
-- Name: users_customuser; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users_customuser (
    id bigint NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL,
    email character varying(254) NOT NULL,
    first_name character varying(50) NOT NULL,
    last_name character varying(50) NOT NULL,
    birth_date date,
    gender character varying(1) NOT NULL,
    avatar character varying(100)
);


--
-- TOC entry 228 (class 1259 OID 112102)
-- Name: users_customuser_groups; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users_customuser_groups (
    id bigint NOT NULL,
    customuser_id bigint NOT NULL,
    group_id integer NOT NULL
);


--
-- TOC entry 227 (class 1259 OID 112101)
-- Name: users_customuser_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users_customuser_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_customuser_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 225 (class 1259 OID 112093)
-- Name: users_customuser_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users_customuser ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_customuser_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 230 (class 1259 OID 112108)
-- Name: users_customuser_user_permissions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users_customuser_user_permissions (
    id bigint NOT NULL,
    customuser_id bigint NOT NULL,
    permission_id integer NOT NULL
);


--
-- TOC entry 229 (class 1259 OID 112107)
-- Name: users_customuser_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users_customuser_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_customuser_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 232 (class 1259 OID 112114)
-- Name: users_userprogress; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users_userprogress (
    id bigint NOT NULL,
    weight double precision NOT NULL,
    height double precision NOT NULL,
    date_recorded timestamp with time zone NOT NULL,
    user_id bigint NOT NULL
);


--
-- TOC entry 231 (class 1259 OID 112113)
-- Name: users_userprogress_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users_userprogress ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_userprogress_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 5098 (class 0 OID 112054)
-- Dependencies: 222
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- TOC entry 5100 (class 0 OID 112062)
-- Dependencies: 224
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- TOC entry 5096 (class 0 OID 112048)
-- Dependencies: 220
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add log entry	1	add_logentry
2	Can change log entry	1	change_logentry
3	Can delete log entry	1	delete_logentry
4	Can view log entry	1	view_logentry
5	Can add permission	2	add_permission
6	Can change permission	2	change_permission
7	Can delete permission	2	delete_permission
8	Can view permission	2	view_permission
9	Can add group	3	add_group
10	Can change group	3	change_group
11	Can delete group	3	delete_group
12	Can view group	3	view_group
13	Can add content type	4	add_contenttype
14	Can change content type	4	change_contenttype
15	Can delete content type	4	delete_contenttype
16	Can view content type	4	view_contenttype
17	Can add session	5	add_session
18	Can change session	5	change_session
19	Can delete session	5	delete_session
20	Can view session	5	view_session
21	Can add Оборудование	6	add_equipment
22	Can change Оборудование	6	change_equipment
23	Can delete Оборудование	6	delete_equipment
24	Can view Оборудование	6	view_equipment
25	Can add Группа мышц	7	add_musclegroup
26	Can change Группа мышц	7	change_musclegroup
27	Can delete Группа мышц	7	delete_musclegroup
28	Can view Группа мышц	7	view_musclegroup
29	Can add Упражнение	8	add_exercise
30	Can change Упражнение	8	change_exercise
31	Can delete Упражнение	8	delete_exercise
32	Can view Упражнение	8	view_exercise
33	Can add day exercise	9	add_dayexercise
34	Can change day exercise	9	change_dayexercise
35	Can delete day exercise	9	delete_dayexercise
36	Can view day exercise	9	view_dayexercise
37	Can add workout day	10	add_workoutday
38	Can change workout day	10	change_workoutday
39	Can delete workout day	10	delete_workoutday
40	Can view workout day	10	view_workoutday
41	Can add workout plan	11	add_workoutplan
42	Can change workout plan	11	change_workoutplan
43	Can delete workout plan	11	delete_workoutplan
44	Can view workout plan	11	view_workoutplan
45	Can add user	12	add_customuser
46	Can change user	12	change_customuser
47	Can delete user	12	delete_customuser
48	Can view user	12	view_customuser
49	Can add Прогресс пользователя	13	add_userprogress
50	Can change Прогресс пользователя	13	change_userprogress
51	Can delete Прогресс пользователя	13	delete_userprogress
52	Can view Прогресс пользователя	13	view_userprogress
53	Can add workout log	14	add_workoutlog
54	Can change workout log	14	change_workoutlog
55	Can delete workout log	14	delete_workoutlog
56	Can view workout log	14	view_workoutlog
57	Can add progress entry	15	add_progressentry
58	Can change progress entry	15	change_progressentry
59	Can delete progress entry	15	delete_progressentry
60	Can view progress entry	15	view_progressentry
\.


--
-- TOC entry 5110 (class 0 OID 112155)
-- Dependencies: 234
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
\.


--
-- TOC entry 5094 (class 0 OID 112040)
-- Dependencies: 218
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	admin	logentry
2	auth	permission
3	auth	group
4	contenttypes	contenttype
5	sessions	session
6	exercises	equipment
7	exercises	musclegroup
8	exercises	exercise
9	training	dayexercise
10	training	workoutday
11	training	workoutplan
12	users	customuser
13	users	userprogress
14	progress	workoutlog
15	progress	progressentry
\.


--
-- TOC entry 5092 (class 0 OID 112032)
-- Dependencies: 216
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	contenttypes	0001_initial	2026-03-18 16:51:11.3518+03
2	contenttypes	0002_remove_content_type_name	2026-03-18 16:51:11.3518+03
3	auth	0001_initial	2026-03-18 16:51:11.385752+03
4	auth	0002_alter_permission_name_max_length	2026-03-18 16:51:11.400745+03
5	auth	0003_alter_user_email_max_length	2026-03-18 16:51:11.403708+03
6	auth	0004_alter_user_username_opts	2026-03-18 16:51:11.403708+03
7	auth	0005_alter_user_last_login_null	2026-03-18 16:51:11.403708+03
8	auth	0006_require_contenttypes_0002	2026-03-18 16:51:11.403708+03
9	auth	0007_alter_validators_add_error_messages	2026-03-18 16:51:11.41757+03
10	auth	0008_alter_user_username_max_length	2026-03-18 16:51:11.421531+03
11	auth	0009_alter_user_last_name_max_length	2026-03-18 16:51:11.421531+03
12	auth	0010_alter_group_name_max_length	2026-03-18 16:51:11.432359+03
13	auth	0011_update_proxy_permissions	2026-03-18 16:51:11.437431+03
14	auth	0012_alter_user_first_name_max_length	2026-03-18 16:51:11.439436+03
15	users	0001_initial	2026-03-18 16:51:11.480142+03
16	admin	0001_initial	2026-03-18 16:51:11.497111+03
17	admin	0002_logentry_remove_auto_add	2026-03-18 16:51:11.497111+03
18	admin	0003_logentry_add_action_flag_choices	2026-03-18 16:51:11.511851+03
19	exercises	0001_initial	2026-03-18 16:51:11.593297+03
20	sessions	0001_initial	2026-03-18 16:51:11.597354+03
21	training	0001_initial	2026-03-18 16:51:11.608707+03
22	training	0002_initial	2026-03-18 16:51:11.654366+03
23	exercises	0002_exercise_image_url	2026-03-19 20:36:23.900026+03
24	users	0002_customuser_avatar	2026-03-22 19:36:55.839101+03
25	training	0003_alter_dayexercise_options_and_more	2026-03-22 21:07:03.247301+03
26	training	0004_alter_dayexercise_options_alter_dayexercise_reps_and_more	2026-03-23 17:29:31.77317+03
27	progress	0001_initial	2026-03-29 23:13:51.701773+03
28	progress	0002_alter_workoutlog_options	2026-03-29 23:14:29.710968+03
29	exercises	0003_exercise_muscle_groups_and_more	2026-04-02 13:57:14.604203+03
30	exercises	0004_musclegroup_is_group	2026-04-02 14:10:58.997936+03
31	exercises	0005_alter_exercise_image	2026-04-03 14:01:13.583448+03
\.


--
-- TOC entry 5123 (class 0 OID 112279)
-- Dependencies: 247
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
h15vpnazptmkx7h8ts7udvhvklteoyil	.eJxVjEEOwiAQRe_C2pAWHKAu3XsGMsxMpWogKe3KeHfbpAvd_vfef6uI65Lj2mSOE6uLMur0uyWkp5Qd8APLvWqqZZmnpHdFH7TpW2V5XQ_37yBjy1stgQChk3NwlnAASGSBjSfPgcdeeEiWHJF4w-hH6Z0NXaKNW28QnPp8AQMWOKA:1w4etT:Krz41E_2_0s2r6w_cr9cGNxFKEoeZCQxYBuR94geTlw	2026-04-06 16:00:31.981391+03
od9obct24eaog39um8kagmylwpot8ejx	.eJxVjDsOwjAQBe_iGlnrH-tQ0ucM1trr4ACypTipEHeHSCmgfTPzXiLQtpaw9byEmcVFaHH63SKlR6474DvVW5Op1XWZo9wVedAux8b5eT3cv4NCvXxrYnLOmWhURJicBUsO80SejYaBFXoFVmlC1hl5gGS0NWwpJUAEfxbvD9PnNyg:1wApBG:efyTnUxu5-bKbbm9g5J7gpvft2DBK1raH6ITDOULVJk	2026-04-23 16:12:22.291688+03
f5g4bhct91qfdtphwmaj5loq8hz77mv3	.eJxVjDsOwjAQBe_iGlnrH-tQ0ucM1trr4ACypTipEHeHSCmgfTPzXiLQtpaw9byEmcVFaHH63SKlR6474DvVW5Op1XWZo9wVedAux8b5eT3cv4NCvXxrYnLOmWhURJicBUsO80SejYaBFXoFVmlC1hl5gGS0NWwpJUAEfxbvD9PnNyg:1wAttW:vyfMjkBDTXWlsWGVzu9guGpqNu8dIuk3sCi5ST59V7Q	2026-04-23 21:14:22.450944+03
y1hcbt65iw0i7zo54cjsfep75gk5q6ny	.eJxVjDsOwjAQBe_iGlnrH-tQ0ucM1trr4ACypTipEHeHSCmgfTPzXiLQtpaw9byEmcVFaHH63SKlR6474DvVW5Op1XWZo9wVedAux8b5eT3cv4NCvXxrYnLOmWhURJicBUsO80SejYaBFXoFVmlC1hl5gGS0NWwpJUAEfxbvD9PnNyg:1wAv1F:gshdq_hn5ARUVhI6R11BgKu7yJr0tKM8XOgmlcIxc9k	2026-04-23 22:26:25.503536+03
k56b95pbqnxiogdpmt783cq3f5ybgbrp	.eJxVjDsOwjAQBe_iGln-4iQlPWew1t4NDkQxsh1RIO5OIqWA9s28eTMPa0t-rVT8hGxgip1-twDxQcsO8A7LLfOYl1amwHeFH7Tya0aaL4f7F0hQ0_YGBGutDloGJ0ZrhAHraIQOtRI9StdJYaQCh4oc9iJqZTQaiFE4J7rzFq0pv3wsBI38c4bFt7wWNowwV_p8AfbKQqQ:1wBKsu:RFfGgP9TARpS-gjoGjh37qJEXxAdnhkDR0aCu18Nuic	2026-04-12 02:03:32.631928+03
ydjqc3c5igqnrpip3g8knpmruq1c3c7j	.eJxVjE0OwiAYRO_C2hCgYMGle89A-H6QqoGktCvj3W2TLnQzi3lv5i1iWpcS185znEhchBan3w4SPrnugB6p3pvEVpd5Arkr8qBd3hrx63q4fwcl9bKt0Tg10MgB0Dpi8A41Zj0yAtsz6GAwWyYFWQ3KWAQf_BYaIAzJZy8-XwrVOO8:1w66kF:WYp3M5ti4Yr9nTzrbxXDY-EroLFXHhRRliSA43IjZP8	2026-04-10 15:56:59.276312+03
unc5sqkk9t1te2zkw9onylj7hej41dym	.eJxVjEEOwiAQRe_C2pAWHKAu3XsGMsxMpWogKe3KeHfbpAvd_vfef6uI65Lj2mSOE6uLMur0uyWkp5Qd8APLvWqqZZmnpHdFH7TpW2V5XQ_37yBjy1stgQChk3NwlnAASGSBjSfPgcdeeEiWHJF4w-hH6Z0NXaKNW28QnPp8AQMWOKA:1w6oyG:aWQT082TT8zY20eIqOfziXtlHe1FtdB48rrLUlRPdIU	2026-04-12 15:10:24.007357+03
h7vlcy6h3kobba6d1gif5awoqquea2us	.eJxVjE0OwiAYRO_C2hCgYMGle89A-H6QqoGktCvj3W2TLnQzi3lv5i1iWpcS185znEhchBan3w4SPrnugB6p3pvEVpd5Arkr8qBd3hrx63q4fwcl9bKt0Tg10MgB0Dpi8A41Zj0yAtsz6GAwWyYFWQ3KWAQf_BYaIAzJZy8-XwrVOO8:1w7Ye2:lJyMfCrVwWaqw-GYlv-dO2RV8SNsOZ7NZl84kdLNRww	2026-04-14 15:56:34.010642+03
\.


--
-- TOC entry 5112 (class 0 OID 112176)
-- Dependencies: 236
-- Data for Name: exercises_equipment; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.exercises_equipment (id, name, slug) FROM stdin;
1	Собственный вес	sobstvennyij-ves
2	Штанга	shtanga
3	Гантели	ganteli
4	Турник	turnik
5	Тренажер	trenazher
6	Брусья	brusya
7	Скамья	skamya
8	Гиря	girya
9	Стойки	stojki
10	Фитнес-резинки	fitnes-rezinki
\.


--
-- TOC entry 5116 (class 0 OID 112198)
-- Dependencies: 240
-- Data for Name: exercises_exercise; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.exercises_exercise (id, name, slug, description, instructions, benefits, precautions, exercise_type, difficulty, video_url, video_file, image, calories_per_hour, is_active, created_at, updated_at, image_url) FROM stdin;
3	Отжимания на брусьях	otzhimaniya-na-brusyah	Упражнения для развития большой и малой грудных мышц, формирующие объем торса.	1. Примите упор на брусьях, наклоните торс слегка вперед. \r\n2. Опуститесь вниз до легкого растяжения в грудных мышцах. \r\n3. Мощно вытолкните себя вверх, фокусируясь на сокращении груди.			strength	intermediate	https://www.youtube.com/embed/hp8kqtxQTNU?feature=share		exercises/grud/otzhimaniya-na-brusyah.gif	0	t	2026-03-19 15:39:21.56126+03	2026-04-03 17:40:43.462145+03	\N
5	Сведения в кроссовере	svedeniya-v-krossovere	Упражнения для развития большой и малой грудных мышц, формирующие объем торса.	1. Возьмитесь за рукояти верхних блоков и сделайте шаг вперед. \r\n2. Сведите руки перед собой на уровне нижней части груди. \r\n3. Плавно вернитесь в исходное положение, сохраняя небольшой изгиб в локтях.			strength	intermediate	https://www.youtube.com/embed/CN2xHjFmcUM?feature=share		exercises/grud/svedeniya-v-krossovere.gif	0	t	2026-03-19 15:39:21.56364+03	2026-04-03 23:05:48.815145+03	\N
9	Жим штанги узким хватом	zhim-shtangi-uzkim-hvatom	Упражнения для развития большой и малой грудных мышц, формирующие объем торса.	1. Хват на ширине плеч или чуть уже. \r\n2. Опустите штангу к низу груди, прижимая локти к корпусу. \r\n3. Выжмите вверх, акцентируя нагрузку на трицепс и внутреннюю часть груди.			strength	intermediate	https://www.youtube.com/embed/g_AnhUfAv70?feature=share		exercises/grud/zhim-shtangi-uzkim-hvatom.webp	0	t	2026-03-19 15:39:21.574815+03	2026-04-03 16:01:05.776417+03	https://goodlooker.ru/wp-content/uploads/2021/11/Zhim_uzkij_so_shtangoj.gif
11	Подтягивания широким хватом	podtyagivaniya-shirokim-hvatom	Тренировка мощного мышечного корсета спины: широчайших, трапеций и разгибателей.	1. Повисните на перекладине широким хватом. \r\n2. Тянитесь грудью к перекладине, сводя лопатки вместе. \r\n3. Подконтрольно опуститесь в нижнюю точку.			strength	intermediate	https://www.youtube.com/embed/UZAsRPWPZAU?feature=share		exercises/spina/podtyagivaniya-shirokim-hvatom.gif	0	t	2026-03-19 15:39:21.574815+03	2026-04-03 22:00:09.731957+03	\N
16	Становая тяга	stanovaya-tyaga	Тренировка мощного мышечного корсета спины: широчайших, трапеций и разгибателей.	1. Поставьте стопы на ширине плеч, возьмитесь за гриф. \r\n2. Поднимайте штангу, одновременно разгибая ноги и спину, держите гриф близко к голеням. \r\n3. Полностью выпрямитесь, отведя плечи назад.			strength	expert	https://www.youtube.com/embed/MPEpQwGTv48?feature=share		exercises/spina/stanovaya-tyaga.gif	0	t	2026-03-19 15:39:21.606263+03	2026-04-03 23:16:20.240839+03	\N
8	Пуловер с гантелью	pulover-s-gantelyu	Упражнения для развития большой и малой грудных мышц, формирующие объем торса.	1. Лягте лопатками поперек скамьи, держите гантель над собой. \r\n2. Опустите гантель за голову на прямых руках до комфортного растяжения. \r\n3. Верните гантель в исходное положение силой широчайших и грудных.			strength	intermediate	https://www.youtube.com/embed/py2zAzuSI68?feature=share		exercises/grud/pulover-s-gantelyu.gif	0	t	2026-03-19 15:39:21.574815+03	2026-04-03 22:44:44.169269+03	\N
15	Тяга горизонтального блока	tyaga-gorizontalnogo-bloka	Тренировка мощного мышечного корсета спины: широчайших, трапеций и разгибателей.	1. Упритесь стопами, держите спину прямой. \r\n2. Тяните рукоять к животу, максимально сводя лопатки в конечной точке. \r\n3. Медленно выпрямите руки, не подавая плечи сильно вперед.			strength	beginner	https://www.youtube.com/embed/X2z3siCh9VE?feature=share		exercises/spina/tyaga-gorizontalnogo-bloka.gif	0	t	2026-03-19 15:39:21.590534+03	2026-04-03 23:26:45.52852+03	\N
18	Тяга Т-грифа	tyaga-t-grifa	Тренировка мощного мышечного корсета спины: широчайших, трапеций и разгибателей.	1. Встаньте над грифом, ноги согнуты. \r\n2. Тяните рукояти к животу, стараясь работать лопатками, а не руками. \r\n3. Опустите вес под контролем.			strength	intermediate	https://www.youtube.com/embed/z-wSKTUFjY4?feature=share		exercises/spina/tyaga-t-grifa.gif	0	t	2026-03-19 15:39:21.606263+03	2026-04-03 23:29:31.37278+03	\N
2	Жим гантелей на наклонной	zhim-gantelej-na-naklonnoj	Упражнения для развития большой и малой грудных мышц, формирующие объем торса.	Жим гантелей на наклонной: 1. Установите скамью на 30-45 градусов. \r\n2. Опускайте гантели по дуге до уровня плеч. \r\n3. Жмите вверх, сводя гантели над грудью.			strength	intermediate	https://www.youtube.com/embed/baU50hfnmEM?feature=share		exercises/grud/zhim-gantelej-na-naklonnoj.webp	0	t	2026-03-19 15:39:21.559085+03	2026-04-03 15:50:29.61185+03	https://gymcoach.ru/wp-content/uploads/2023/04/ezgif-5-0bd0f2e06f-y.gif
19	Шраги со штангой	shragi-so-shtangoj	Тренировка мощного мышечного корсета спины: широчайших, трапеций и разгибателей.	1. Держите штангу в прямых руках перед собой. \r\n2. Поднимайте плечи строго вверх к ушам. \r\n3. Задержитесь вверху и плавно опустите плечи вниз.			strength	beginner	https://www.youtube.com/embed/tM_p0lia4I4?feature=share		exercises/spina/shragi-so-shtangoj.gif	0	t	2026-03-19 15:39:21.606263+03	2026-04-03 23:42:09.063055+03	\N
39	Молотки с гантелями	molotki-s-gantelyami	Изолированная проработка мышц рук (бицепса и трицепса) для увеличения объема.	1. Гантели в руках ладонями к корпусу (нейтральный хват). \r\n2. Поднимайте гантели, сохраняя положение ладоней «друг на друга». \r\n3. Опустите под контролем.			strength	beginner	https://www.youtube.com/embed/Lc-dGbMlI7A?feature=share		exercises/ruki/molotki-s-gantelyami.gif	0	t	2026-03-19 15:39:21.696006+03	2026-04-03 17:38:23.174528+03	\N
24	Мертвая тяга	mertvaya-tyaga	Базовая проработка нижней части тела: квадрицепсов, бицепса бедра и ягодичных мышц.	1. Держите штангу, ноги почти прямые. \r\n2. Опускайте гриф вдоль ног до середины голени, отводя таз назад. \r\n3. Вернитесь вверх за счет усилия бицепсов бедра и ягодиц.			strength	advanced	https://www.youtube.com/embed/uq8B9E7rjmI?feature=share		exercises/nogi/mertvaya-tyaga.gif	0	t	2026-03-19 15:39:21.63791+03	2026-04-03 17:36:22.672097+03	\N
25	Разгибания ног в тренажере	razgibaniya-nog-v-trenazhere	Базовая проработка нижней части тела: квадрицепсов, бицепса бедра и ягодичных мышц.	1. Сядьте плотно, валик над голеностопом. \r\n2. Полностью выпрямите ноги, напрягая квадрицепсы. \r\n3. Плавно опустите валик вниз.			strength	beginner	https://www.youtube.com/embed/P7tyoHwFRR4?feature=share		exercises/nogi/razgibaniya-nog-v-trenazhere.gif	0	t	2026-03-19 15:39:21.63791+03	2026-04-03 23:03:14.111875+03	\N
34	Махи в наклоне	mahi-v-naklone	Акцент на дельтовидные мышцы для создания широкого и эстетичного V-образного силуэта.	1. Сильно наклонитесь вперед, спина прямая. \r\n2. Разводите гантели в стороны, концентрируясь на заднем пучке дельт. \r\n3. Подконтрольно опустите руки.			strength	intermediate	https://www.youtube.com/embed/ITYTv6wI4lM?feature=share		exercises/plechi/mahi-v-naklone.gif	0	t	2026-03-19 15:39:21.669762+03	2026-04-03 16:52:33.048857+03	\N
26	Сгибания ног лежа	sgibaniya-nog-lezha	Базовая проработка нижней части тела: квадрицепсов, бицепса бедра и ягодичных мышц.	1. Лягте на тренажер, валик под пятками. \r\n2. Максимально согните ноги, стараясь коснуться валиком ягодиц. \r\n3. Медленно опустите ноги.			strength	beginner	https://www.youtube.com/embed/kTATod98psM?feature=share		exercises/nogi/sgibaniya-nog-lezha.gif	0	t	2026-03-19 15:39:21.63791+03	2026-04-03 23:09:31.2983+03	\N
27	Подъемы на носки стоя	podemyi-na-noski-stoya	Базовая проработка нижней части тела: квадрицепсов, бицепса бедра и ягодичных мышц.	1. Встаньте носками на край платформы. \r\n2. Опустите пятки максимально низко для растяжения. \r\n3. Мощно поднимитесь на носки до пикового сокращения икр.			strength	beginner	https://www.youtube.com/embed/2_D_vANfH28?feature=share		exercises/nogi/podemyi-na-noski-stoya.gif	0	t	2026-03-19 15:39:21.63791+03	2026-04-03 22:24:08.474312+03	\N
33	Махи гантелями в стороны	mahi-gantelyami-v-storonyi	Акцент на дельтовидные мышцы для создания широкого и эстетичного V-образного силуэта.	1. Слегка наклонитесь вперед, руки чуть согнуты. \r\n2. Поднимите гантели через стороны до уровня плеч (мизинец выше большого пальца). \r\n3. Плавно опустите.			strength	beginner	https://www.youtube.com/embed/DfggQm5hfs4?feature=share		exercises/plechi/mahi-gantelyami-v-storonyi.jpg	0	t	2026-03-19 15:39:21.669762+03	2026-04-03 16:55:35.21012+03	\N
22	Жим ногами	zhim-nogami	Базовая проработка нижней части тела: квадрицепсов, бицепса бедра и ягодичных мышц.	1. Прижмите поясницу к сиденью, стопы на платформе. \r\n2. Опустите платформу до прямого угла в коленях. \r\n3. Выжмите платформу вверх, не выпрямляя колени до щелчка.			strength	intermediate	https://www.youtube.com/embed/NuCWXAZLLgw?feature=share		exercises/nogi/zhim-nogami.gif	0	t	2026-03-19 15:39:21.623049+03	2026-04-03 15:55:11.690042+03	https://gymbot.ru/wp-content/uploads/2024/06/ezgif-1-e23de50cee.gif
35	Тяга штанги к подбородку	tyaga-shtangi-k-podborodku	Акцент на дельтовидные мышцы для создания широкого и эстетичного V-образного силуэта.	1. Хват на ширине плеч. \r\n2. Тяните штангу вверх вдоль тела, разводя локти в стороны и вверх. \r\n3. Опустите до полного выпрямления рук.			strength	intermediate	https://www.youtube.com/embed/ENOWauy-mbI?feature=share		exercises/plechi/tyaga-shtangi-k-podborodku.gif	0	t	2026-03-19 15:39:21.669762+03	2026-04-03 23:36:58.471545+03	\N
21	Приседания со штангой	prisedaniya-so-shtangoj	Базовая проработка нижней части тела: квадрицепсов, бицепса бедра и ягодичных мышц.	1. Штанга на трапециях, стопы чуть шире плеч. \r\n2. Опускайтесь до параллели бедер с полом, держа спину прямой. \r\n3. Встаньте, упираясь в пятки.			strength	advanced	https://www.youtube.com/embed/Iw5oDuAQhdE?feature=share		exercises/nogi/prisedaniya-so-shtangoj.gif	0	t	2026-03-19 15:39:21.623049+03	2026-04-03 22:41:49.448512+03	\N
32	Жим гантелей сидя	zhim-gantelej-sidya	Акцент на дельтовидные мышцы для создания широкого и эстетичного V-образного силуэта.	1. Спинка скамьи вертикальна. \r\n2. Жмите гантели вверх по дуге, не ударяя их друг о друга. \r\n3. Опускайте до уровня ушей.			strength	intermediate	https://www.youtube.com/embed/naKbU_OzUVE?feature=share		exercises/plechi/zhim-gantelej-sidya.gif	0	t	2026-03-19 15:39:21.669762+03	2026-04-03 15:53:22.195647+03	https://gymcoach.ru/wp-content/uploads/2023/04/ezgif-3-239b3d9a6e.gif
42	Концентрированный подъем	kontsentrirovannyij-podem	Изолированная проработка мышц рук (бицепса и трицепса) для увеличения объема.	1. Сядьте, уприте локоть во внутреннюю часть бедра. \r\n2. Согните руку с гантелью к плечу. \r\n3. Плавно разогните.			strength	intermediate	https://www.youtube.com/embed/7iPz9d_JggY?feature=share		exercises/ruki/kontsentrirovannyij-podem.gif	0	t	2026-03-19 15:39:21.701448+03	2026-04-03 16:15:18.217674+03	\N
43	Отжимания от скамьи	otzhimaniya-ot-skami	Изолированная проработка мышц рук (бицепса и трицепса) для увеличения объема.	1. Упор руками сзади о край скамьи, ноги вытянуты. \r\n2. Опуститесь вниз, сгибая локти до 90°. \r\n3. Мощно вытолкните себя вверх.			strength	beginner	https://www.youtube.com/embed/85OGIVrccuI?feature=share		exercises/ruki/otzhimaniya-ot-skami.gif	0	t	2026-03-19 15:39:21.701448+03	2026-04-03 17:46:53.833615+03	\N
7	Жим в Хаммере	zhim-v-hammere	Упражнения для развития большой и малой грудных мышц, формирующие объем торса.	1. Плотно прижмите спину к спинке тренажера. \r\n2. Выжмите рукояти вперед до полного выпрямления рук (без фиксации локтей). \r\n3. Подконтрольно вернитесь назад, не допуская удара веса.			strength	beginner	https://www.youtube.com/embed/EC1Yf3M0im8?feature=share		exercises/grud/zhim-v-hammere.gif	0	t	2026-03-19 15:39:21.574815+03	2026-04-03 15:46:30.704356+03	https://gymbot.ru/images/687f709537365_chest-press-machine__1_.gif
45	Планка	planka	Упражнения для укрепления мышц брюшного пресса и стабилизации корпуса.	1. Упор на предплечья и носки. \r\n2. Тело в одну прямую линию без прогиба в пояснице. \r\n3. Напрягите живот и ягодицы.			strength	beginner	https://www.youtube.com/embed/xfmEXowXKxs?feature=share		exercises/press/planka.jpg	0	t	2026-03-19 15:39:21.717103+03	2026-04-03 17:52:35.540736+03	\N
46	Подъем ног в висе	podem-nog-v-vise	Упражнения для укрепления мышц брюшного пресса и стабилизации корпуса.	1. Повисните на перекладине. \r\n2. Поднимите прямые или согнутые ноги выше уровня таза. \r\n3. Медленно опустите, избегая раскачки.			strength	intermediate	https://www.youtube.com/embed/Y398S5WuN_Q?feature=share		exercises/press/podem-nog-v-vise.gif	0	t	2026-03-19 15:39:21.717103+03	2026-04-03 22:14:26.117898+03	\N
44	Скручивания	skruchivaniya	Упражнения для укрепления мышц брюшного пресса и стабилизации корпуса.	1. Лежа на спине, ноги согнуты. \r\n2. Оторвите лопатки от пола, скручивая корпус к тазу (поясница прижата). \r\n3. Плавно вернитесь назад.			strength	beginner	https://www.youtube.com/embed/rWrSk8-6YZY?feature=share		exercises/press/skruchivaniya.gif	0	t	2026-03-19 15:39:21.701448+03	2026-04-03 23:11:58.859453+03	\N
23	Выпады с гантелями	vyipadyi-s-gantelyami	Базовая проработка нижней части тела: квадрицепсов, бицепса бедра и ягодичных мышц.	1. Сделайте широкий шаг вперед. \r\n2. Опуститесь так, чтобы оба колена образовали угол 90°. \r\n3. Вернитесь в исходное положение толчком передней ноги.			strength	intermediate	https://www.youtube.com/embed/ShJ8Er-lQvs?feature=share		exercises/nogi/vyipadyi-s-gantelyami.gif	0	t	2026-03-19 15:39:21.623049+03	2026-04-03 15:34:14.233704+03	https://goodlooker.ru/wp-content/uploads/2021/05/Vypady_vpered_s_gantelyami_2.gif
41	Разгибания на верхнем блоке	razgibaniya-na-verhnem-bloke	Изолированная проработка мышц рук (бицепса и трицепса) для увеличения объема.	1. Возьмитесь за рукоять, локти зафиксированы у ребер. \r\n2. Полностью выпрямите руки вниз. \r\n3. Плавно верните рукоять до уровня груди.			strength	beginner	https://www.youtube.com/embed/XarMK6Gp930?feature=share		exercises/ruki/razgibaniya-na-verhnem-bloke.gif	0	t	2026-03-19 15:39:21.701448+03	2026-04-03 22:57:44.978972+03	\N
47	Велосипед	velosiped	Упражнения для укрепления мышц брюшного пресса и стабилизации корпуса.	1. Лежа на спине, руки за головой. \r\n2. Тянитесь правым локтем к левому колену, имитируя кручение педалей. \r\n3. Повторите для другой стороны.			strength	beginner	https://rutube.ru/play/embed/966d1355e825566db6509b617a67c228/		exercises/press/velosiped.gif	0	t	2026-03-19 15:39:21.717103+03	2026-04-03 15:22:20.590027+03	https://goodlooker.ru/wp-content/uploads/2021/01/Velosiped_new.gif
17	Гиперэкстензия	giperekstenziya	Тренировка мощного мышечного корсета спины: широчайших, трапеций и разгибателей.	1. Зафиксируйте ноги, держите спину прямой. \r\n2. Опустите корпус вниз до угла 90°, не округляя поясницу. \r\n3. Поднимитесь до прямой линии с ногами			warmup	beginner	https://www.youtube.com/embed/1SGDltWoJv4?feature=share		exercises/spina/giperekstenziya.gif	0	t	2026-03-19 15:39:21.606263+03	2026-04-03 15:41:34.706461+03	https://goodlooker.ru/wp-content/uploads/2020/10/Superman_ruki_nazad.gif
29	Зашагивания на платформу	zashagivaniya-na-platformu	Базовая проработка нижней части тела: квадрицепсов, бицепса бедра и ягодичных мышц.	1. Поставьте одну ногу на тумбу. \r\n2. Силой рабочей ноги поднимите тело вверх. \r\n3. Подконтрольно спуститесь обратно.			strength	beginner	https://www.youtube.com/embed/aFvpwzqkTZU?feature=share		exercises/nogi/zashagivaniya-na-platformu.gif	0	t	2026-03-19 15:39:21.654918+03	2026-04-03 16:04:34.558+03	https://gymbot.ru/images/68be87404a0e5_weighted-step-up.gif
37	Подъем гантелей перед собой	podem-gantelej-pered-soboj	Акцент на дельтовидные мышцы для создания широкого и эстетичного V-образного силуэта.	1. Стойте ровно, гантели на бедрах. \r\n2. Поднимите прямые руки перед собой до уровня глаз.\r\n3. Плавно опустите вниз.			strength	beginner	https://www.youtube.com/embed/IBdgvqbiWW0?feature=share		exercises/plechi/podem-gantelej-pered-soboj.jpg	0	t	2026-03-19 15:39:21.685587+03	2026-04-03 22:05:16.717516+03	\N
36	Жим Арнольда	zhim-arnolda	Акцент на дельтовидные мышцы для создания широкого и эстетичного V-образного силуэта.	1. Держите гантели перед лицом ладонями к себе. \r\n2. Жмите вверх, разворачивая кисти ладонями от себя. \r\n3. В верхней точке руки полностью выпрямлены.			strength	advanced	https://www.youtube.com/embed/AzVXLJrBOoM?feature=share		exercises/plechi/zhim-arnolda.gif	0	t	2026-03-19 15:39:21.669762+03	2026-04-03 15:40:47.833736+03	https://goodlooker.ru/wp-content/uploads/2020/04/Zhim_arnolda_sidya.gif
40	Французский жим	frantsuzskij-zhim	Изолированная проработка мышц рук (бицепса и трицепса) для увеличения объема.	1. Лежа на скамье, держите штангу узким хватом над собой. \r\n2. Сгибая локти, опустите гриф ко лбу. \r\n3. Выпрямите руки только за счет трицепсов.			strength	intermediate	https://www.youtube.com/embed/gxfIb3K7d10?feature=share		exercises/ruki/frantsuzskij-zhim.gif	0	t	2026-03-19 15:39:21.699442+03	2026-04-03 23:39:48.54804+03	\N
10	Бабочка	babochka	Упражнения для развития большой и малой грудных мышц, формирующие объем торса.	1. Примите устойчивое исходное положение. \r\n2. Выполните движение плавно и подконтрольно. \r\n3. Вернитесь в начальную точку.			strength	beginner	https://www.youtube.com/embed/d0xbXpJSF98?feature=share		exercises/grud/babochka.gif	0	t	2026-03-19 15:39:21.574815+03	2026-04-03 14:04:54.804575+03	https://gymbot.ru/wp-content/uploads/2024/06/ezgif-3-38c04458d7.gif
31	Армейский жим	armejskij-zhim	Акцент на дельтовидные мышцы для создания широкого и эстетичного V-образного силуэта.	Армейский жим: \r\n1. Жмите штангу вертикально вверх от груди стоя. \r\n2. В верхней точке голова чуть подается вперед. \r\n3. Не прогибайте поясницу.			strength	intermediate	https://www.youtube.com/embed/8jBvJc5pMuI?feature=share		exercises/plechi/armejskij-zhim.gif	0	t	2026-03-19 15:39:21.654918+03	2026-04-03 14:19:14.573401+03	https://vashsport.com/wp-content/uploads/2019/03/armeyskiy-zhim-shtangi-stoya-vashsport.com_.gif
28	Гакк-приседания	gakk-prisedaniya	Базовая проработка нижней части тела: квадрицепсов, бицепса бедра и ягодичных мышц.	1. Прижмитесь к платформе тренажера. \r\n2. Медленно присядьте до параллели. \r\n3. Выжмите себя вверх, сохраняя нажим всей стопой.			strength	advanced	https://www.youtube.com/embed/FPi5uy0GYB0?feature=share		exercises/nogi/gakk-prisedaniya.gif	0	t	2026-03-19 15:39:21.654918+03	2026-04-03 15:34:44.046593+03	https://gymbot.ru/images/68891d82b4415_hack-squat-musculature.gif
1	Жим штанги лежа	zhim-shtangi-lezha	Упражнения для развития большой и малой грудных мышц, формирующие объем торса.	1. Лягте на скамью, сведите лопатки и возьмите штангу хватом чуть шире плеч. \r\n2. Опустите гриф до касания нижней части груди, держа локти под углом 45°. \r\n3. Мощно выжмите штангу вверх, не отрывая таз от скамьи.			strength	intermediate	https://www.youtube.com/embed/jWdzYreqKLc?feature=share		exercises/grud/zhim-shtangi-lezha.gif	0	t	2026-03-19 15:39:21.543384+03	2026-04-03 15:56:49.148627+03	https://gymbot.ru/images/685570388663d_barbell-floor-press.gif
30	Приседания плие	prisedaniya-plie	Базовая проработка нижней части тела: квадрицепсов, бицепса бедра и ягодичных мышц.	1. Широкая постановка ног, носки развернуты наружу, гантель в руках между ног. \r\n2. Глубоко присядьте, чувствуя растяжение внутренней части бедра. \r\n3. Встаньте, сжимая ягодицы.			strength	intermediate	https://www.youtube.com/embed/rygf04WI01c?feature=share		exercises/nogi/prisedaniya-plie.gif	0	t	2026-03-19 15:39:21.654918+03	2026-04-03 22:38:42.832809+03	\N
14	Тяга верхнего блока к груди	tyaga-verhnego-bloka-k-grudi	Тренировка мощного мышечного корсета спины: широчайших, трапеций и разгибателей.	1. Сядьте в тренажер, возьмитесь за рукоять широким хватом. \r\n2. Тяните рукоять к верхней части груди, отклоняясь слегка назад. \r\n3. Плавно верните вес вверх.			strength	beginner	https://www.youtube.com/embed/l5w-FXVchYc?feature=share		exercises/spina/tyaga-verhnego-bloka-k-grudi.gif	0	t	2026-03-19 15:39:21.590534+03	2026-04-03 23:20:02.176157+03	\N
13	Тяга гантели одной рукой	tyaga-ganteli-odnoj-rukoj	Тренировка мощного мышечного корсета спины: широчайших, трапеций и разгибателей.	1. Упритесь коленом и рукой в скамью, спина параллельна полу. \r\n2. Тяните гантель к карману брюк, поднимая локоть максимально высоко. \r\n3. Опустите гантель вниз до полного растяжения.			strength	intermediate	https://www.youtube.com/embed/BXqSt8E0VEE?feature=share		exercises/spina/tyaga-ganteli-odnoj-rukoj.gif	0	t	2026-03-19 15:39:21.590534+03	2026-04-03 23:23:34.254143+03	\N
48	Ножницы	nozhnicy	Упражнение представляет собой поочередное скрещивание прямых ног на небольшой высоте от пола. В отличие от обычных подъемов ног, «Ножницы» создают длительное статическое напряжение в мышцах пресса, заставляя их работать на удержание веса конечностей.	1. Исходное положение: Лягте на спину на коврик. Руки вытяните вдоль туловища ладонями вниз (для поддержки поясницы можно положить ладони под ягодицы).\r\n\r\n2. Начало движения: Плотно прижмите поясницу к полу. Поднимите обе ноги над полом на высоту 15–30 см. Ноги должны быть прямыми, носки вытянуты.\r\n\r\n3. Выполнение: Разведите ноги в стороны, а затем сведите их обратно так, чтобы одна нога оказалась над другой (скрещивание). Сразу же снова разведите ноги и поменяйте их положение (если правая была сверху, теперь левая идет наверх).\r\n\r\n4. Дыхание: Дышите ровно и ритмично. Не задерживайте дыхание во время выполнения.			strength	intermediate	https://www.youtube.com/embed/zt5w4kcUCHU?feature=share		exercises/press/nozhnicy.gif	0	t	2026-03-19 15:39:21.717103+03	2026-04-03 16:11:54.022403+03	\N
20	Лодочка	lodochka	Тренировка мощного мышечного корсета спины: широчайших, трапеций и разгибателей.	1. Лягте на живот, руки вытянуты вперед. \r\n2. Одновременно оторвите прямые руки и ноги от пола. \r\n3. Задержитесь на 2-3 секунды и медленно опуститесь.			strength	beginner	https://www.youtube.com/embed/zUlNlOLnhRs?feature=share		exercises/spina/lodochka.gif	0	t	2026-03-19 15:39:21.623049+03	2026-04-03 16:20:31.079472+03	\N
6	Отжимания от пола	otzhimaniya-ot-pola	Упражнения для развития большой и малой грудных мышц, формирующие объем торса.	1. Примите упор лежа, руки чуть шире плеч, тело — прямая линия. \r\n2. Опуститесь грудью почти до пола, локти направлены назад и в стороны. \r\n3. Выдохните и вернитесь в исходное положение.			strength	beginner	https://www.youtube.com/embed/ADrt90yNi-o?feature=share		exercises/grud/otzhimaniya-ot-pola.gif	0	t	2026-03-19 15:39:21.56364+03	2026-04-03 17:44:38.053131+03	\N
38	Подъем штанги на бицепс	podem-shtangi-na-bitseps	Изолированная проработка мышц рук (бицепса и трицепса) для увеличения объема.	1. Хват снизу, локти прижаты к бокам. \r\n2. Согните руки, поднимая штангу к плечам без раскачки корпуса. \r\n3. Медленно опустите.			strength	beginner	https://www.youtube.com/embed/fC5H-hjBbv4?feature=share		exercises/ruki/podem-shtangi-na-bitseps.gif	0	t	2026-03-19 15:39:21.685587+03	2026-04-03 22:18:30.585685+03	\N
4	Разводка гантелей	razvodka-gantelej	Упражнения для развития большой и малой грудных мышц, формирующие объем торса.	1. Лежа на скамье, держите гантели над грудью слегка согнутыми руками. \r\n2. Разведите руки в стороны до уровня плеч, чувствуя растяжение. \r\n3. Сведите гантели обратно, имитируя объятие большого дерева.			strength	beginner	https://www.youtube.com/embed/fSm2cFVsfcU?feature=share		exercises/grud/razvodka-gantelej.gif	0	t	2026-03-19 15:39:21.56364+03	2026-04-03 22:54:51.049278+03	\N
12	Тяга штанги в наклоне	tyaga-shtangi-v-naklone	Тренировка мощного мышечного корсета спины: широчайших, трапеций и разгибателей.	1. Наклонитесь с прямой спиной под 45°, возьмите штангу. \r\n2. Тяните гриф к поясу, ведя локти вдоль корпуса. \r\n3. Плавно опустите снаряд, растягивая спину.			strength	advanced	https://www.youtube.com/embed/VJwPkJHDLrc?feature=share		exercises/spina/tyaga-shtangi-v-naklone.gif	0	t	2026-03-19 15:39:21.590534+03	2026-04-03 23:31:39.834316+03	\N
\.


--
-- TOC entry 5118 (class 0 OID 112211)
-- Dependencies: 242
-- Data for Name: exercises_exercise_equipment; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.exercises_exercise_equipment (id, exercise_id, equipment_id) FROM stdin;
1	1	2
2	2	3
3	3	6
4	4	3
5	5	5
6	6	1
7	7	5
8	8	3
9	9	2
10	10	5
11	11	4
12	12	2
13	13	3
14	14	5
15	15	5
16	16	2
17	17	1
18	18	5
19	19	2
20	20	1
21	21	2
22	22	5
23	23	3
24	24	2
25	25	5
26	26	5
27	27	5
28	28	5
29	29	1
30	30	3
31	31	2
32	32	3
33	33	3
34	34	3
35	35	2
36	36	3
37	37	3
38	38	2
39	39	3
40	40	2
41	41	5
42	42	3
43	43	7
44	44	1
45	45	1
46	46	4
47	47	1
48	48	1
49	17	5
50	30	8
51	30	2
52	44	5
53	35	5
\.


--
-- TOC entry 5135 (class 0 OID 112382)
-- Dependencies: 259
-- Data for Name: exercises_exercise_muscle_groups; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.exercises_exercise_muscle_groups (id, exercise_id, musclegroup_id) FROM stdin;
1	31	4
2	10	1
3	7	1
4	2	1
5	1	1
6	9	1
7	3	1
8	6	1
9	8	1
10	4	1
11	5	1
12	17	2
13	20	2
14	11	2
15	16	2
16	14	2
17	13	2
18	15	2
19	18	2
20	12	2
21	19	2
22	23	3
23	28	3
24	22	3
25	29	3
26	24	3
27	27	3
28	30	3
29	21	3
30	25	3
31	26	3
33	36	4
34	32	4
35	34	4
36	33	4
37	37	4
38	35	4
39	42	5
40	39	5
41	43	5
42	38	5
43	41	5
44	40	5
45	47	6
46	48	6
47	45	6
48	46	6
49	44	6
\.


--
-- TOC entry 5120 (class 0 OID 112217)
-- Dependencies: 244
-- Data for Name: exercises_exercise_primary_muscles; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.exercises_exercise_primary_muscles (id, exercise_id, musclegroup_id) FROM stdin;
7	7	1
9	9	1
47	47	6
48	48	6
51	1	7
52	2	7
53	3	7
54	3	16
55	4	7
56	6	7
57	10	7
58	11	9
59	12	9
60	12	10
61	14	9
62	16	11
63	16	20
64	17	11
65	21	18
66	21	20
67	22	18
68	23	20
69	23	18
70	24	19
71	25	18
72	31	12
73	31	13
74	32	12
75	33	13
76	34	14
77	36	12
78	38	15
79	39	15
80	40	16
81	41	16
82	43	16
83	44	6
84	45	6
85	46	6
86	28	18
87	28	20
88	28	23
89	7	12
90	9	16
91	29	18
92	29	20
93	48	18
94	42	15
95	20	11
96	37	12
97	27	21
98	30	20
99	30	23
100	8	9
101	8	7
102	5	7
103	26	19
104	13	9
105	15	9
106	18	9
107	35	10
108	35	13
109	19	10
\.


--
-- TOC entry 5122 (class 0 OID 112223)
-- Dependencies: 246
-- Data for Name: exercises_exercise_secondary_muscles; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.exercises_exercise_secondary_muscles (id, exercise_id, musclegroup_id) FROM stdin;
1	1	12
2	1	16
3	2	12
4	2	16
5	3	12
6	4	12
7	6	16
8	6	12
9	10	12
10	11	15
11	11	17
12	12	15
13	12	14
14	14	15
15	14	17
16	16	10
17	16	19
18	17	20
19	17	19
20	21	19
21	21	21
22	22	20
23	23	19
24	24	20
25	24	11
26	31	16
27	31	10
28	32	16
29	33	12
30	33	10
31	34	10
32	36	16
33	36	13
34	38	17
35	39	17
36	43	12
37	44	22
38	45	18
39	45	4
40	28	19
41	28	6
42	7	16
43	9	12
44	29	19
45	48	22
46	42	17
47	20	10
48	20	19
49	20	20
50	24	21
51	37	10
52	37	13
53	37	7
54	46	12
55	46	22
56	30	18
57	30	19
58	30	21
59	8	16
60	8	10
61	8	14
62	41	17
63	5	17
64	5	12
65	5	6
66	26	20
67	26	21
68	13	10
69	13	11
70	13	14
71	13	15
72	15	17
73	15	10
74	15	11
75	15	14
76	18	10
77	18	11
78	18	14
79	18	15
80	35	17
81	35	12
82	35	15
83	40	17
84	40	12
85	19	17
86	19	11
\.


--
-- TOC entry 5114 (class 0 OID 112186)
-- Dependencies: 238
-- Data for Name: exercises_musclegroup; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.exercises_musclegroup (id, name, slug, description, icon, is_group) FROM stdin;
9	Широчайшие	shirochajshie		\N	f
10	Трапеции	trapecii		\N	f
11	Поясница	poyasnica		\N	f
12	Передняя дельта	perednyaya-delta		\N	f
13	Средняя дельта	srednyaya-delta		\N	f
14	Задняя дельта	zadnyaya-delta		\N	f
15	Бицепс	biceps		\N	f
16	Трицепс	triceps		\N	f
17	Предплечья	predplechya		\N	f
18	Квадрицепс	kvadriceps		\N	f
19	Бицепс бедра	biceps-bedra		\N	f
20	Ягодицы	yagodicy		\N	f
21	Икры	ikry		\N	f
22	Косые мышцы живота	kosye-myshcy-zhivota		\N	f
1	Грудь	grud	Большие и малые грудные мышцы	\N	t
3	Ноги	nogi	Квадрицепсы, бицепс бедра и икры	\N	t
4	Плечи	plechi	Передние, средние и задние дельты	\N	t
6	Пресс	press	Прямая и косые мышцы живота	\N	t
2	Спина	spina	Широчайшие, трапеции и выпрямители спины	\N	t
5	Руки	ruki	Бицепс, трицепс и предплечья	\N	t
7	Грудные	grudnye		\N	f
23	Приводящие мышцы бедра	privodyashie-myshcy-bedra		\N	f
\.


--
-- TOC entry 5133 (class 0 OID 112356)
-- Dependencies: 257
-- Data for Name: progress_progressentry; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.progress_progressentry (id, image, weight, comment, created_at, user_id) FROM stdin;
61	progress_photos/2026/04/Снимок_экрана_2023-08-28_132758_Y6aeJbX.png	2.00	2	2026-04-07	2
62	progress_photos/2026/04/Снимок_экрана_2023-09-11_001310.png	1.00	khhhhhh	2026-04-09	2
16	progress_photos/2026/03/f0607d867a3fd368e063868447cb10a1_nc3i3Oj.jpg	90.00	ну да я тупо я	2026-03-31	2
25	progress_photos/2026/03/images_1.jpeg	90.00	Празднично	2026-03-31	2
26	progress_photos/2026/03/images_2.jpeg	14.00	Круто	2026-03-31	2
32	progress_photos/2026/04/Снимок_экрана_2023-08-28_132758.png	90.00	лоло	2026-04-07	2
49	progress_photos/2026/04/Снимок_экрана_2023-08-02_031243_PYowBLR.png	3.00		2026-04-07	2
50	progress_photos/2026/04/Снимок_экрана_2023-08-02_031243_3hPST1f.png	3.00		2026-04-07	2
\.


--
-- TOC entry 5131 (class 0 OID 112350)
-- Dependencies: 255
-- Data for Name: progress_workoutlog; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.progress_workoutlog (id, completed_at, user_id, workout_day_id) FROM stdin;
53	2026-04-10 12:41:08.201712+03	2	218
\.


--
-- TOC entry 5125 (class 0 OID 112289)
-- Dependencies: 249
-- Data for Name: training_dayexercise; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.training_dayexercise (id, exercise_id, workout_day_id, "order", reps, sets) FROM stdin;
235	31	218	0	12	3
\.


--
-- TOC entry 5127 (class 0 OID 112295)
-- Dependencies: 251
-- Data for Name: training_workoutday; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.training_workoutday (id, day_number, plan_id) FROM stdin;
218	5	65
\.


--
-- TOC entry 5129 (class 0 OID 112302)
-- Dependencies: 253
-- Data for Name: training_workoutplan; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.training_workoutplan (id, title, start_date, end_date, created_at, user_id, is_active) FROM stdin;
65	набор массы	2026-04-01	2026-04-23	2026-04-10 12:40:57.708881+03	2	t
\.


--
-- TOC entry 5102 (class 0 OID 112094)
-- Dependencies: 226
-- Data for Name: users_customuser; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.users_customuser (id, password, last_login, is_superuser, is_staff, is_active, date_joined, email, first_name, last_name, birth_date, gender, avatar) FROM stdin;
2	pbkdf2_sha256$600000$zAw2Ss9Mej76A1Sqc9Dcqr$I1jHHnxHv+Uz6IscHIumXvgtNR+SqasANTMy3qD8lM4=	2026-04-09 22:26:25.4927+03	f	f	t	2026-03-19 14:03:38.201184+03	simakov_zhorochka@mail.ru	Егор	Симаков	\N		avatars/2026/04/Снимок_экрана_2024-08-19_233220.png
\.


--
-- TOC entry 5104 (class 0 OID 112102)
-- Dependencies: 228
-- Data for Name: users_customuser_groups; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.users_customuser_groups (id, customuser_id, group_id) FROM stdin;
\.


--
-- TOC entry 5106 (class 0 OID 112108)
-- Dependencies: 230
-- Data for Name: users_customuser_user_permissions; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.users_customuser_user_permissions (id, customuser_id, permission_id) FROM stdin;
\.


--
-- TOC entry 5108 (class 0 OID 112114)
-- Dependencies: 232
-- Data for Name: users_userprogress; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.users_userprogress (id, weight, height, date_recorded, user_id) FROM stdin;
2	90	189	2026-03-24 21:12:28.848066+03	2
\.


--
-- TOC entry 5142 (class 0 OID 0)
-- Dependencies: 221
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- TOC entry 5143 (class 0 OID 0)
-- Dependencies: 223
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- TOC entry 5144 (class 0 OID 0)
-- Dependencies: 219
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 60, true);


--
-- TOC entry 5145 (class 0 OID 0)
-- Dependencies: 233
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 139, true);


--
-- TOC entry 5146 (class 0 OID 0)
-- Dependencies: 217
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 15, true);


--
-- TOC entry 5147 (class 0 OID 0)
-- Dependencies: 215
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 31, true);


--
-- TOC entry 5148 (class 0 OID 0)
-- Dependencies: 235
-- Name: exercises_equipment_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.exercises_equipment_id_seq', 10, true);


--
-- TOC entry 5149 (class 0 OID 0)
-- Dependencies: 241
-- Name: exercises_exercise_equipment_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.exercises_exercise_equipment_id_seq', 53, true);


--
-- TOC entry 5150 (class 0 OID 0)
-- Dependencies: 239
-- Name: exercises_exercise_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.exercises_exercise_id_seq', 48, true);


--
-- TOC entry 5151 (class 0 OID 0)
-- Dependencies: 258
-- Name: exercises_exercise_muscle_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.exercises_exercise_muscle_groups_id_seq', 49, true);


--
-- TOC entry 5152 (class 0 OID 0)
-- Dependencies: 243
-- Name: exercises_exercise_primary_muscles_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.exercises_exercise_primary_muscles_id_seq', 109, true);


--
-- TOC entry 5153 (class 0 OID 0)
-- Dependencies: 245
-- Name: exercises_exercise_secondary_muscles_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.exercises_exercise_secondary_muscles_id_seq', 86, true);


--
-- TOC entry 5154 (class 0 OID 0)
-- Dependencies: 237
-- Name: exercises_musclegroup_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.exercises_musclegroup_id_seq', 23, true);


--
-- TOC entry 5155 (class 0 OID 0)
-- Dependencies: 256
-- Name: progress_progressentry_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.progress_progressentry_id_seq', 62, true);


--
-- TOC entry 5156 (class 0 OID 0)
-- Dependencies: 254
-- Name: progress_workoutlog_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.progress_workoutlog_id_seq', 53, true);


--
-- TOC entry 5157 (class 0 OID 0)
-- Dependencies: 248
-- Name: training_dayexercise_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.training_dayexercise_id_seq', 235, true);


--
-- TOC entry 5158 (class 0 OID 0)
-- Dependencies: 250
-- Name: training_workoutday_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.training_workoutday_id_seq', 218, true);


--
-- TOC entry 5159 (class 0 OID 0)
-- Dependencies: 252
-- Name: training_workoutplan_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.training_workoutplan_id_seq', 65, true);


--
-- TOC entry 5160 (class 0 OID 0)
-- Dependencies: 227
-- Name: users_customuser_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.users_customuser_groups_id_seq', 1, false);


--
-- TOC entry 5161 (class 0 OID 0)
-- Dependencies: 225
-- Name: users_customuser_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.users_customuser_id_seq', 2, true);


--
-- TOC entry 5162 (class 0 OID 0)
-- Dependencies: 229
-- Name: users_customuser_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.users_customuser_user_permissions_id_seq', 1, false);


--
-- TOC entry 5163 (class 0 OID 0)
-- Dependencies: 231
-- Name: users_userprogress_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.users_userprogress_id_seq', 2, true);


--
-- TOC entry 4816 (class 2606 OID 112091)
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- TOC entry 4821 (class 2606 OID 112077)
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- TOC entry 4824 (class 2606 OID 112066)
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- TOC entry 4818 (class 2606 OID 112058)
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- TOC entry 4811 (class 2606 OID 112068)
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- TOC entry 4813 (class 2606 OID 112052)
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- TOC entry 4847 (class 2606 OID 112162)
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- TOC entry 4806 (class 2606 OID 112046)
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- TOC entry 4808 (class 2606 OID 112044)
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- TOC entry 4804 (class 2606 OID 112038)
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- TOC entry 4896 (class 2606 OID 112285)
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- TOC entry 4851 (class 2606 OID 112182)
-- Name: exercises_equipment exercises_equipment_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.exercises_equipment
    ADD CONSTRAINT exercises_equipment_name_key UNIQUE (name);


--
-- TOC entry 4853 (class 2606 OID 112180)
-- Name: exercises_equipment exercises_equipment_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.exercises_equipment
    ADD CONSTRAINT exercises_equipment_pkey PRIMARY KEY (id);


--
-- TOC entry 4856 (class 2606 OID 112184)
-- Name: exercises_equipment exercises_equipment_slug_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.exercises_equipment
    ADD CONSTRAINT exercises_equipment_slug_key UNIQUE (slug);


--
-- TOC entry 4877 (class 2606 OID 112238)
-- Name: exercises_exercise_equipment exercises_exercise_equip_exercise_id_equipment_id_14c08b66_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.exercises_exercise_equipment
    ADD CONSTRAINT exercises_exercise_equip_exercise_id_equipment_id_14c08b66_uniq UNIQUE (exercise_id, equipment_id);


--
-- TOC entry 4881 (class 2606 OID 112215)
-- Name: exercises_exercise_equipment exercises_exercise_equipment_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.exercises_exercise_equipment
    ADD CONSTRAINT exercises_exercise_equipment_pkey PRIMARY KEY (id);


--
-- TOC entry 4918 (class 2606 OID 112388)
-- Name: exercises_exercise_muscle_groups exercises_exercise_muscl_exercise_id_musclegroup__7de19e0d_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.exercises_exercise_muscle_groups
    ADD CONSTRAINT exercises_exercise_muscl_exercise_id_musclegroup__7de19e0d_uniq UNIQUE (exercise_id, musclegroup_id);


--
-- TOC entry 4922 (class 2606 OID 112386)
-- Name: exercises_exercise_muscle_groups exercises_exercise_muscle_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.exercises_exercise_muscle_groups
    ADD CONSTRAINT exercises_exercise_muscle_groups_pkey PRIMARY KEY (id);


--
-- TOC entry 4870 (class 2606 OID 112207)
-- Name: exercises_exercise exercises_exercise_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.exercises_exercise
    ADD CONSTRAINT exercises_exercise_name_key UNIQUE (name);


--
-- TOC entry 4872 (class 2606 OID 112205)
-- Name: exercises_exercise exercises_exercise_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.exercises_exercise
    ADD CONSTRAINT exercises_exercise_pkey PRIMARY KEY (id);


--
-- TOC entry 4883 (class 2606 OID 112252)
-- Name: exercises_exercise_primary_muscles exercises_exercise_prima_exercise_id_musclegroup__0e23b9e6_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.exercises_exercise_primary_muscles
    ADD CONSTRAINT exercises_exercise_prima_exercise_id_musclegroup__0e23b9e6_uniq UNIQUE (exercise_id, musclegroup_id);


--
-- TOC entry 4887 (class 2606 OID 112221)
-- Name: exercises_exercise_primary_muscles exercises_exercise_primary_muscles_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.exercises_exercise_primary_muscles
    ADD CONSTRAINT exercises_exercise_primary_muscles_pkey PRIMARY KEY (id);


--
-- TOC entry 4889 (class 2606 OID 112266)
-- Name: exercises_exercise_secondary_muscles exercises_exercise_secon_exercise_id_musclegroup__23aecfdb_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.exercises_exercise_secondary_muscles
    ADD CONSTRAINT exercises_exercise_secon_exercise_id_musclegroup__23aecfdb_uniq UNIQUE (exercise_id, musclegroup_id);


--
-- TOC entry 4893 (class 2606 OID 112227)
-- Name: exercises_exercise_secondary_muscles exercises_exercise_secondary_muscles_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.exercises_exercise_secondary_muscles
    ADD CONSTRAINT exercises_exercise_secondary_muscles_pkey PRIMARY KEY (id);


--
-- TOC entry 4875 (class 2606 OID 112209)
-- Name: exercises_exercise exercises_exercise_slug_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.exercises_exercise
    ADD CONSTRAINT exercises_exercise_slug_key UNIQUE (slug);


--
-- TOC entry 4859 (class 2606 OID 112194)
-- Name: exercises_musclegroup exercises_musclegroup_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.exercises_musclegroup
    ADD CONSTRAINT exercises_musclegroup_name_key UNIQUE (name);


--
-- TOC entry 4861 (class 2606 OID 112192)
-- Name: exercises_musclegroup exercises_musclegroup_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.exercises_musclegroup
    ADD CONSTRAINT exercises_musclegroup_pkey PRIMARY KEY (id);


--
-- TOC entry 4864 (class 2606 OID 112196)
-- Name: exercises_musclegroup exercises_musclegroup_slug_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.exercises_musclegroup
    ADD CONSTRAINT exercises_musclegroup_slug_key UNIQUE (slug);


--
-- TOC entry 4915 (class 2606 OID 112362)
-- Name: progress_progressentry progress_progressentry_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.progress_progressentry
    ADD CONSTRAINT progress_progressentry_pkey PRIMARY KEY (id);


--
-- TOC entry 4911 (class 2606 OID 112354)
-- Name: progress_workoutlog progress_workoutlog_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.progress_workoutlog
    ADD CONSTRAINT progress_workoutlog_pkey PRIMARY KEY (id);


--
-- TOC entry 4900 (class 2606 OID 112293)
-- Name: training_dayexercise training_dayexercise_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.training_dayexercise
    ADD CONSTRAINT training_dayexercise_pkey PRIMARY KEY (id);


--
-- TOC entry 4903 (class 2606 OID 112300)
-- Name: training_workoutday training_workoutday_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.training_workoutday
    ADD CONSTRAINT training_workoutday_pkey PRIMARY KEY (id);


--
-- TOC entry 4905 (class 2606 OID 112328)
-- Name: training_workoutday training_workoutday_plan_id_day_number_c9bcbc33_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.training_workoutday
    ADD CONSTRAINT training_workoutday_plan_id_day_number_c9bcbc33_uniq UNIQUE (plan_id, day_number);


--
-- TOC entry 4908 (class 2606 OID 112306)
-- Name: training_workoutplan training_workoutplan_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.training_workoutplan
    ADD CONSTRAINT training_workoutplan_pkey PRIMARY KEY (id);


--
-- TOC entry 4827 (class 2606 OID 112100)
-- Name: users_customuser users_customuser_email_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_customuser
    ADD CONSTRAINT users_customuser_email_key UNIQUE (email);


--
-- TOC entry 4832 (class 2606 OID 112121)
-- Name: users_customuser_groups users_customuser_groups_customuser_id_group_id_76b619e3_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_customuser_groups
    ADD CONSTRAINT users_customuser_groups_customuser_id_group_id_76b619e3_uniq UNIQUE (customuser_id, group_id);


--
-- TOC entry 4835 (class 2606 OID 112106)
-- Name: users_customuser_groups users_customuser_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_customuser_groups
    ADD CONSTRAINT users_customuser_groups_pkey PRIMARY KEY (id);


--
-- TOC entry 4829 (class 2606 OID 112098)
-- Name: users_customuser users_customuser_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_customuser
    ADD CONSTRAINT users_customuser_pkey PRIMARY KEY (id);


--
-- TOC entry 4837 (class 2606 OID 112135)
-- Name: users_customuser_user_permissions users_customuser_user_pe_customuser_id_permission_7a7debf6_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_customuser_user_permissions
    ADD CONSTRAINT users_customuser_user_pe_customuser_id_permission_7a7debf6_uniq UNIQUE (customuser_id, permission_id);


--
-- TOC entry 4841 (class 2606 OID 112112)
-- Name: users_customuser_user_permissions users_customuser_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_customuser_user_permissions
    ADD CONSTRAINT users_customuser_user_permissions_pkey PRIMARY KEY (id);


--
-- TOC entry 4843 (class 2606 OID 112118)
-- Name: users_userprogress users_userprogress_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_userprogress
    ADD CONSTRAINT users_userprogress_pkey PRIMARY KEY (id);


--
-- TOC entry 4814 (class 1259 OID 112092)
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- TOC entry 4819 (class 1259 OID 112088)
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- TOC entry 4822 (class 1259 OID 112089)
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- TOC entry 4809 (class 1259 OID 112074)
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- TOC entry 4845 (class 1259 OID 112173)
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- TOC entry 4848 (class 1259 OID 112174)
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- TOC entry 4894 (class 1259 OID 112287)
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- TOC entry 4897 (class 1259 OID 112286)
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- TOC entry 4865 (class 1259 OID 112236)
-- Name: exercises_e_difficu_1e38ee_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX exercises_e_difficu_1e38ee_idx ON public.exercises_exercise USING btree (difficulty);


--
-- TOC entry 4866 (class 1259 OID 112235)
-- Name: exercises_e_exercis_697236_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX exercises_e_exercis_697236_idx ON public.exercises_exercise USING btree (exercise_type);


--
-- TOC entry 4867 (class 1259 OID 112234)
-- Name: exercises_e_name_9bce89_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX exercises_e_name_9bce89_idx ON public.exercises_exercise USING btree (name);


--
-- TOC entry 4849 (class 1259 OID 112228)
-- Name: exercises_equipment_name_0d1853dd_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX exercises_equipment_name_0d1853dd_like ON public.exercises_equipment USING btree (name varchar_pattern_ops);


--
-- TOC entry 4854 (class 1259 OID 112229)
-- Name: exercises_equipment_slug_1f848fc9_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX exercises_equipment_slug_1f848fc9_like ON public.exercises_equipment USING btree (slug varchar_pattern_ops);


--
-- TOC entry 4878 (class 1259 OID 112250)
-- Name: exercises_exercise_equipment_equipment_id_c79a7b44; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX exercises_exercise_equipment_equipment_id_c79a7b44 ON public.exercises_exercise_equipment USING btree (equipment_id);


--
-- TOC entry 4879 (class 1259 OID 112249)
-- Name: exercises_exercise_equipment_exercise_id_4d1976c3; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX exercises_exercise_equipment_exercise_id_4d1976c3 ON public.exercises_exercise_equipment USING btree (exercise_id);


--
-- TOC entry 4919 (class 1259 OID 112399)
-- Name: exercises_exercise_muscle_groups_exercise_id_928526c5; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX exercises_exercise_muscle_groups_exercise_id_928526c5 ON public.exercises_exercise_muscle_groups USING btree (exercise_id);


--
-- TOC entry 4920 (class 1259 OID 112400)
-- Name: exercises_exercise_muscle_groups_musclegroup_id_38bd5b1d; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX exercises_exercise_muscle_groups_musclegroup_id_38bd5b1d ON public.exercises_exercise_muscle_groups USING btree (musclegroup_id);


--
-- TOC entry 4868 (class 1259 OID 112232)
-- Name: exercises_exercise_name_d52987aa_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX exercises_exercise_name_d52987aa_like ON public.exercises_exercise USING btree (name varchar_pattern_ops);


--
-- TOC entry 4884 (class 1259 OID 112263)
-- Name: exercises_exercise_primary_muscles_exercise_id_f96f88d9; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX exercises_exercise_primary_muscles_exercise_id_f96f88d9 ON public.exercises_exercise_primary_muscles USING btree (exercise_id);


--
-- TOC entry 4885 (class 1259 OID 112264)
-- Name: exercises_exercise_primary_muscles_musclegroup_id_a2aa3b12; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX exercises_exercise_primary_muscles_musclegroup_id_a2aa3b12 ON public.exercises_exercise_primary_muscles USING btree (musclegroup_id);


--
-- TOC entry 4890 (class 1259 OID 112277)
-- Name: exercises_exercise_secondary_muscles_exercise_id_2151d323; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX exercises_exercise_secondary_muscles_exercise_id_2151d323 ON public.exercises_exercise_secondary_muscles USING btree (exercise_id);


--
-- TOC entry 4891 (class 1259 OID 112278)
-- Name: exercises_exercise_secondary_muscles_musclegroup_id_2123625e; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX exercises_exercise_secondary_muscles_musclegroup_id_2123625e ON public.exercises_exercise_secondary_muscles USING btree (musclegroup_id);


--
-- TOC entry 4873 (class 1259 OID 112233)
-- Name: exercises_exercise_slug_3dfbe879_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX exercises_exercise_slug_3dfbe879_like ON public.exercises_exercise USING btree (slug varchar_pattern_ops);


--
-- TOC entry 4857 (class 1259 OID 112230)
-- Name: exercises_musclegroup_name_538f01d6_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX exercises_musclegroup_name_538f01d6_like ON public.exercises_musclegroup USING btree (name varchar_pattern_ops);


--
-- TOC entry 4862 (class 1259 OID 112231)
-- Name: exercises_musclegroup_slug_06421f95_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX exercises_musclegroup_slug_06421f95_like ON public.exercises_musclegroup USING btree (slug varchar_pattern_ops);


--
-- TOC entry 4916 (class 1259 OID 112380)
-- Name: progress_progressentry_user_id_d0db6855; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX progress_progressentry_user_id_d0db6855 ON public.progress_progressentry USING btree (user_id);


--
-- TOC entry 4912 (class 1259 OID 112373)
-- Name: progress_workoutlog_user_id_b52179b6; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX progress_workoutlog_user_id_b52179b6 ON public.progress_workoutlog USING btree (user_id);


--
-- TOC entry 4913 (class 1259 OID 112374)
-- Name: progress_workoutlog_workout_day_id_a0dd22d8; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX progress_workoutlog_workout_day_id_a0dd22d8 ON public.progress_workoutlog USING btree (workout_day_id);


--
-- TOC entry 4898 (class 1259 OID 112331)
-- Name: training_dayexercise_exercise_id_cdedfbe7; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX training_dayexercise_exercise_id_cdedfbe7 ON public.training_dayexercise USING btree (exercise_id);


--
-- TOC entry 4901 (class 1259 OID 112332)
-- Name: training_dayexercise_workout_day_id_6b28a26e; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX training_dayexercise_workout_day_id_6b28a26e ON public.training_dayexercise USING btree (workout_day_id);


--
-- TOC entry 4906 (class 1259 OID 112330)
-- Name: training_workoutday_plan_id_eaaf0817; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX training_workoutday_plan_id_eaaf0817 ON public.training_workoutday USING btree (plan_id);


--
-- TOC entry 4909 (class 1259 OID 112329)
-- Name: training_workoutplan_user_id_4a58c9ec; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX training_workoutplan_user_id_4a58c9ec ON public.training_workoutplan USING btree (user_id);


--
-- TOC entry 4825 (class 1259 OID 112119)
-- Name: users_customuser_email_6445acef_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX users_customuser_email_6445acef_like ON public.users_customuser USING btree (email varchar_pattern_ops);


--
-- TOC entry 4830 (class 1259 OID 112132)
-- Name: users_customuser_groups_customuser_id_958147bf; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX users_customuser_groups_customuser_id_958147bf ON public.users_customuser_groups USING btree (customuser_id);


--
-- TOC entry 4833 (class 1259 OID 112133)
-- Name: users_customuser_groups_group_id_01390b14; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX users_customuser_groups_group_id_01390b14 ON public.users_customuser_groups USING btree (group_id);


--
-- TOC entry 4838 (class 1259 OID 112146)
-- Name: users_customuser_user_permissions_customuser_id_5771478b; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX users_customuser_user_permissions_customuser_id_5771478b ON public.users_customuser_user_permissions USING btree (customuser_id);


--
-- TOC entry 4839 (class 1259 OID 112147)
-- Name: users_customuser_user_permissions_permission_id_baaa2f74; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX users_customuser_user_permissions_permission_id_baaa2f74 ON public.users_customuser_user_permissions USING btree (permission_id);


--
-- TOC entry 4844 (class 1259 OID 112153)
-- Name: users_userprogress_user_id_3af9d33f; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX users_userprogress_user_id_3af9d33f ON public.users_userprogress USING btree (user_id);


--
-- TOC entry 4924 (class 2606 OID 112083)
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4925 (class 2606 OID 112078)
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4923 (class 2606 OID 112069)
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4931 (class 2606 OID 112163)
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4932 (class 2606 OID 112168)
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_users_customuser_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_users_customuser_id FOREIGN KEY (user_id) REFERENCES public.users_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4933 (class 2606 OID 112244)
-- Name: exercises_exercise_equipment exercises_exercise_e_equipment_id_c79a7b44_fk_exercises; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.exercises_exercise_equipment
    ADD CONSTRAINT exercises_exercise_e_equipment_id_c79a7b44_fk_exercises FOREIGN KEY (equipment_id) REFERENCES public.exercises_equipment(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4934 (class 2606 OID 112239)
-- Name: exercises_exercise_equipment exercises_exercise_e_exercise_id_4d1976c3_fk_exercises; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.exercises_exercise_equipment
    ADD CONSTRAINT exercises_exercise_e_exercise_id_4d1976c3_fk_exercises FOREIGN KEY (exercise_id) REFERENCES public.exercises_exercise(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4946 (class 2606 OID 112389)
-- Name: exercises_exercise_muscle_groups exercises_exercise_m_exercise_id_928526c5_fk_exercises; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.exercises_exercise_muscle_groups
    ADD CONSTRAINT exercises_exercise_m_exercise_id_928526c5_fk_exercises FOREIGN KEY (exercise_id) REFERENCES public.exercises_exercise(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4947 (class 2606 OID 112394)
-- Name: exercises_exercise_muscle_groups exercises_exercise_m_musclegroup_id_38bd5b1d_fk_exercises; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.exercises_exercise_muscle_groups
    ADD CONSTRAINT exercises_exercise_m_musclegroup_id_38bd5b1d_fk_exercises FOREIGN KEY (musclegroup_id) REFERENCES public.exercises_musclegroup(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4935 (class 2606 OID 112253)
-- Name: exercises_exercise_primary_muscles exercises_exercise_p_exercise_id_f96f88d9_fk_exercises; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.exercises_exercise_primary_muscles
    ADD CONSTRAINT exercises_exercise_p_exercise_id_f96f88d9_fk_exercises FOREIGN KEY (exercise_id) REFERENCES public.exercises_exercise(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4936 (class 2606 OID 112258)
-- Name: exercises_exercise_primary_muscles exercises_exercise_p_musclegroup_id_a2aa3b12_fk_exercises; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.exercises_exercise_primary_muscles
    ADD CONSTRAINT exercises_exercise_p_musclegroup_id_a2aa3b12_fk_exercises FOREIGN KEY (musclegroup_id) REFERENCES public.exercises_musclegroup(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4937 (class 2606 OID 112267)
-- Name: exercises_exercise_secondary_muscles exercises_exercise_s_exercise_id_2151d323_fk_exercises; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.exercises_exercise_secondary_muscles
    ADD CONSTRAINT exercises_exercise_s_exercise_id_2151d323_fk_exercises FOREIGN KEY (exercise_id) REFERENCES public.exercises_exercise(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4938 (class 2606 OID 112272)
-- Name: exercises_exercise_secondary_muscles exercises_exercise_s_musclegroup_id_2123625e_fk_exercises; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.exercises_exercise_secondary_muscles
    ADD CONSTRAINT exercises_exercise_s_musclegroup_id_2123625e_fk_exercises FOREIGN KEY (musclegroup_id) REFERENCES public.exercises_musclegroup(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4945 (class 2606 OID 112375)
-- Name: progress_progressentry progress_progressentry_user_id_d0db6855_fk_users_customuser_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.progress_progressentry
    ADD CONSTRAINT progress_progressentry_user_id_d0db6855_fk_users_customuser_id FOREIGN KEY (user_id) REFERENCES public.users_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4943 (class 2606 OID 112363)
-- Name: progress_workoutlog progress_workoutlog_user_id_b52179b6_fk_users_customuser_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.progress_workoutlog
    ADD CONSTRAINT progress_workoutlog_user_id_b52179b6_fk_users_customuser_id FOREIGN KEY (user_id) REFERENCES public.users_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4944 (class 2606 OID 112368)
-- Name: progress_workoutlog progress_workoutlog_workout_day_id_a0dd22d8_fk_training_; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.progress_workoutlog
    ADD CONSTRAINT progress_workoutlog_workout_day_id_a0dd22d8_fk_training_ FOREIGN KEY (workout_day_id) REFERENCES public.training_workoutday(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4939 (class 2606 OID 112317)
-- Name: training_dayexercise training_dayexercise_exercise_id_cdedfbe7_fk_exercises; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.training_dayexercise
    ADD CONSTRAINT training_dayexercise_exercise_id_cdedfbe7_fk_exercises FOREIGN KEY (exercise_id) REFERENCES public.exercises_exercise(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4940 (class 2606 OID 112322)
-- Name: training_dayexercise training_dayexercise_workout_day_id_6b28a26e_fk_training_; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.training_dayexercise
    ADD CONSTRAINT training_dayexercise_workout_day_id_6b28a26e_fk_training_ FOREIGN KEY (workout_day_id) REFERENCES public.training_workoutday(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4941 (class 2606 OID 112312)
-- Name: training_workoutday training_workoutday_plan_id_eaaf0817_fk_training_workoutplan_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.training_workoutday
    ADD CONSTRAINT training_workoutday_plan_id_eaaf0817_fk_training_workoutplan_id FOREIGN KEY (plan_id) REFERENCES public.training_workoutplan(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4942 (class 2606 OID 112307)
-- Name: training_workoutplan training_workoutplan_user_id_4a58c9ec_fk_users_customuser_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.training_workoutplan
    ADD CONSTRAINT training_workoutplan_user_id_4a58c9ec_fk_users_customuser_id FOREIGN KEY (user_id) REFERENCES public.users_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4926 (class 2606 OID 112122)
-- Name: users_customuser_groups users_customuser_gro_customuser_id_958147bf_fk_users_cus; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_customuser_groups
    ADD CONSTRAINT users_customuser_gro_customuser_id_958147bf_fk_users_cus FOREIGN KEY (customuser_id) REFERENCES public.users_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4927 (class 2606 OID 112127)
-- Name: users_customuser_groups users_customuser_groups_group_id_01390b14_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_customuser_groups
    ADD CONSTRAINT users_customuser_groups_group_id_01390b14_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4928 (class 2606 OID 112136)
-- Name: users_customuser_user_permissions users_customuser_use_customuser_id_5771478b_fk_users_cus; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_customuser_user_permissions
    ADD CONSTRAINT users_customuser_use_customuser_id_5771478b_fk_users_cus FOREIGN KEY (customuser_id) REFERENCES public.users_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4929 (class 2606 OID 112141)
-- Name: users_customuser_user_permissions users_customuser_use_permission_id_baaa2f74_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_customuser_user_permissions
    ADD CONSTRAINT users_customuser_use_permission_id_baaa2f74_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4930 (class 2606 OID 112148)
-- Name: users_userprogress users_userprogress_user_id_3af9d33f_fk_users_customuser_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_userprogress
    ADD CONSTRAINT users_userprogress_user_id_3af9d33f_fk_users_customuser_id FOREIGN KEY (user_id) REFERENCES public.users_customuser(id) DEFERRABLE INITIALLY DEFERRED;


-- Completed on 2026-04-13 17:09:34

--
-- PostgreSQL database dump complete
--

