# Generated by Django 6.0.1 on 2026-02-05 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Оборудование',
                'verbose_name_plural': 'Оборудование',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MuscleGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Группа мышц',
                'verbose_name_plural': 'Группы мышц',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField()),
                ('instructions', models.TextField(blank=True)),
                ('benefits', models.TextField(blank=True)),
                ('precautions', models.TextField(blank=True)),
                ('exercise_type', models.CharField(choices=[('strength', 'Силовое'), ('cardio', 'Кардио'), ('flexibility', 'Растяжка'), ('balance', 'Баланс'), ('warmup', 'Разминка'), ('cooldown', 'Заминка')], default='strength', max_length=20)),
                ('difficulty', models.CharField(choices=[('beginner', 'Начинающий'), ('intermediate', 'Средний'), ('advanced', 'Продвинутый'), ('expert', 'Эксперт')], default='beginner', max_length=20)),
                ('video_url', models.URLField(blank=True)),
                ('video_file', models.FileField(blank=True, null=True, upload_to='exercise_videos/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='exercise_images/')),
                ('calories_per_hour', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('equipment', models.ManyToManyField(blank=True, to='exercises.equipment')),
                ('primary_muscles', models.ManyToManyField(related_name='primary_exercises', to='exercises.musclegroup')),
                ('secondary_muscles', models.ManyToManyField(blank=True, related_name='secondary_exercises', to='exercises.musclegroup')),
            ],
            options={
                'verbose_name': 'Упражнение',
                'verbose_name_plural': 'Упражнения',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='exercises_e_name_9bce89_idx'), models.Index(fields=['exercise_type'], name='exercises_e_exercis_697236_idx'), models.Index(fields=['difficulty'], name='exercises_e_difficu_1e38ee_idx')],
            },
        ),
    ]
