# Generated by Django 4.2.7 on 2026-04-02 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0002_exercise_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='muscle_groups',
            field=models.ManyToManyField(related_name='grouped_exercises', to='exercises.musclegroup', verbose_name='Группы мышц (общие)'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='primary_muscles',
            field=models.ManyToManyField(related_name='primary_exercises', to='exercises.musclegroup', verbose_name='Основные мышцы (детально)'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='secondary_muscles',
            field=models.ManyToManyField(blank=True, related_name='secondary_exercises', to='exercises.musclegroup', verbose_name='Вторичные мышцы (детально)'),
        ),
    ]
