# Generated by Django 4.2.7 on 2026-04-02 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0003_exercise_muscle_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='musclegroup',
            name='is_group',
            field=models.BooleanField(default=False, help_text='Отметьте, если это крупная категория (например, Плечи, Грудь), а не отдельная мышца.', verbose_name='Это основная группа'),
        ),
    ]
