# Generated by Django 4.2.7 on 2026-04-03 11:01

from django.db import migrations, models
import exercises.models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0004_musclegroup_is_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=exercises.models.exercise_gif_path, verbose_name='GIF-анимация (файл)'),
        ),
    ]
