# Generated by Django 4.2.7 on 2026-03-22 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dayexercise',
            options={'ordering': ['order']},
        ),
        migrations.RemoveField(
            model_name='dayexercise',
            name='sets_reps',
        ),
        migrations.AddField(
            model_name='dayexercise',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dayexercise',
            name='reps',
            field=models.CharField(default='0', max_length=50, verbose_name='Повторения'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dayexercise',
            name='sets',
            field=models.PositiveIntegerField(default=1, verbose_name='Подходы'),
        ),
        migrations.AddField(
            model_name='workoutplan',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='workoutday',
            name='day_number',
            field=models.PositiveIntegerField(choices=[(1, 'ПН'), (2, 'ВТ'), (3, 'СР'), (4, 'ЧТ'), (5, 'ПТ'), (6, 'СБ'), (7, 'ВС')], verbose_name='День недели'),
        ),
    ]
