# Generated by Django 4.2.7 on 2026-03-23 14:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0003_alter_dayexercise_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dayexercise',
            options={'ordering': ['order'], 'verbose_name': 'Упражнение в тренировке', 'verbose_name_plural': 'Упражнения в тренировках'},
        ),
        migrations.AlterField(
            model_name='dayexercise',
            name='reps',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Повторения'),
        ),
        migrations.AlterField(
            model_name='dayexercise',
            name='sets',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Подходы'),
        ),
    ]
